server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php;

    # БАГ 1: Неправильный путь к сокету или порту (вызовет 502)
    location ~ \.php$ {
        fastcgi_pass app:9001; 
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # БАГ 2: Жесткий редирект без исключения для SSL (вызовет ошибку Certbot)
    # Раскомментируй строки ниже для тренировки SSL
    # if ($scheme != "https") {
    #     return 301 https://$host$request_uri;
    # }
}